pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url "https://jitpack.io" }
        maven {url 'https://developer.huawei.com/repo/'}
        maven {
            url "https://maven.google.com"
        }
        //OPPO推送（公开只读凭证，见 OPPO 官方文档）
        maven {
            url 'https://maven.columbus.heytapmobi.com/repository/maven-public/'
            credentials {
                username 'cmuser'
                password 'c0b08da17ery566c3870fed67789bcb36abc2e32'
            }
        }
    }
}
rootProject.name = "TsddClient"
include ':MyLibs:rlottie'
include ':MyLibs:vivopush'
include ':MyLibs:xiaomipush'
include ':app'
include ':wkbase'
include ':wkuikit'
include ':wkscan'
include ':wklogin'
include ':wkpush'
include ':wkim'
